name: Docker Image Creation

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cellulant/${{ github.event.repository.name }}-server:v1.0.0-${GITHUB_SHA::6}-amd64
    - name: Docker Push
      run: docker push cellulant/${{ github.event.repository.name }}-server:v1.0.0-${GITHUB_SHA::6}-amd64
